"""userActions_added

Revision ID: 4fef633a3527
Revises: c8c8ea7e58fe
Create Date: 2024-07-08 12:43:56.442629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fef633a3527'
down_revision = 'c8c8ea7e58fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('useraction', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'useraction', 'asset', ['asset_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'useraction', 'task', ['task_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'useraction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'useraction', 'coproductionprocess', ['coproductionprocess_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useraction', type_='foreignkey')
    op.drop_constraint(None, 'useraction', type_='foreignkey')
    op.drop_constraint(None, 'useraction', type_='foreignkey')
    op.drop_constraint(None, 'useraction', type_='foreignkey')
    op.alter_column('useraction', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
