"""schema coproductionprocess edited for new gamification engine

Revision ID: 66bb2581f96a
Revises: c8c8ea7e58fe
Create Date: 2024-09-13 11:30:26.540809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66bb2581f96a'
down_revision = 'c8c8ea7e58fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useraction')
    op.add_column('coproductionprocess', sa.Column('game_gamification_engine', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'game_gamification_engine')
    op.create_table('useraction',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coproductionprocess_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('asset_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='useraction_pkey')
    )
    # ### end Alembic commands ###
