"""agreeTermsOfUse

Revision ID: c8c8ea7e58fe
Revises: 990a22e75e5e
Create Date: 2024-05-31 12:09:40.589909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c8ea7e58fe'
down_revision = '990a22e75e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agreeTermsOfUse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'agreeTermsOfUse')
    # ### end Alembic commands ###
